version: "3.9"

services:
  sqlserver:
    build: ./db
    container_name: registro-autos-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SuperSecreta123$"
      MSSQL_PID: "Developer"     # o "Express"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data:                    # ← ¡aquí estaba el faltante!
